### ISSUE TITLE
only VC created by dockcerts can be Verified in this verifier??

### ISSUE THREAD

**Issue by Muthurajj** [docknetwork/vcdm-verifier#32]

**Comment by SamHellawell** [comment]
hello, no others can be too - but the DID must be supported by the Dock API. currently we support the DIDs listed at https://dev.uniresolver.io/

the biggest issue with VC adoption is resolving DID documents for others

**Comment by Muthurajj** [comment]
Hi , how to include my public and verifiction type in this??
The verifier only support base58btc encryption??

**Comment by Muthurajj** [comment]
Hi , I have generated VC with unireslover while verifying i am getting "A DID document lookup was successful, but the DID in question does not exist. This is different from a network error" this error do you have any idea ??

This is my diddocument:
{
  "state": "finished",
  "secret": null,
  "didDocument": {
    "@context": "https://www.w3.org/ns/did/v1",
    "authentication": [],
    "service": [
      {
        "type": "ServiceEndpointProxyService",
        "serviceEndpoint": "https://sysveda.co.in"
      }
    ],
    "verificationMethod": [
      {
        "type": "Ed25519VerificationKey2018",
        "publicKeyBase64": "de8777a28f8da1a74e7a13090ed974d879bf692d001cddee16e4cc9f84b60580"
      }
    ],
    "id": "did:web:did-web.uniregistrar.io:dadaa7f5-47f9-430f-a4a7-1074bd1c6508"
  },
  "did": "did:web:did-web.uniregistrar.io:dadaa7f5-47f9-430f-a4a7-1074bd1c6508"
}


This is the generated Vc:

{
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://www.w3.org/2018/credentials/examples/v1"
    ],
    "type": [
        "UniversityDegreeCredential",
        "VerifiableCredential"
    ],
    "issuer": "did:web:did-web.uniregistrar.io:dadaa7f5-47f9-430f-a4a7-1074bd1c6508",
    "issuanceDate": "2019-06-16T18:56:59Z",
    "expirationDate": "2023-06-17T18:56:59Z",
    "credentialSubject": {
        "degree": {
            "name": "Bachelor of Science and Arts",
            "type": "BachelorDegree"
        }
    },
    "proof": {
        "type": "Ed25519Signature2018",
        "created": "2022-09-26T05:25:44Z",
        "proofPurpose": "assertionMethod",
        "verificationMethod": "did:web:did-web.uniregistrar.io:dadaa7f5-47f9-430f-a4a7-1074bd1c6508#keys-1",
        "jws": "eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFZERTQSJ9..pASJSRwohIhieNhMjghlx9Wc_WoAEqZk-Gq6E3YyghIrS-tzq3lL44XA30CVDHtwaolNW9EcQIEUVpq1eo6FCg"
    }
}
